-- +goose Up
-- +goose StatementBegin
CREATE TABLE posts
(
    post_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        TEXT        NOT NULL,
    description  TEXT        NOT NULL,
    slug         TEXT UNIQUE NOT NULL,
    content      TEXT        NOT NULL,
    author_name  TEXT        NOT NULL,
    tags         TEXT[],
    is_published BOOLEAN   DEFAULT FALSE,
    published_at TIMESTAMP,
    created_at   TIMESTAMP DEFAULT NOW(),
    updated_at   TIMESTAMP DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION posts_get(
    p_post_id BIGINT = NULL
)
    RETURNS TABLE
            (
                post_id      BIGINT,
                title        TEXT,
                description TEXT,
                slug         TEXT,
                content      TEXT,
                author_name  TEXT,
                tags         TEXT[],
                published_at TIMESTAMP
            )
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF p_post_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.post_id = p_post_id) THEN
        RAISE EXCEPTION 'Post does not exist' USING ERRCODE = 'P0001';
    END IF;

    RETURN QUERY (SELECT p.post_id,
                         p.title,
                         p.description,
                         p.slug,
                         p.content,
                         p.author_name,
                         p.tags,
                         p.published_at
                  FROM posts p
                  WHERE is_published = TRUE
                    AND (
                      p_post_id IS NULL
                          OR
                      p.post_id = p_post_id
                      ));
END
$$;

CREATE OR REPLACE FUNCTION posts_insert(
    p_title TEXT,
    p_description TEXT,
    p_slug TEXT,
    p_content TEXT,
    p_author_name TEXT,
    p_tags TEXT[],
    p_is_published BOOLEAN
)
    RETURNS VOID
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF EXISTS (SELECT 1 FROM posts WHERE slug = p_slug) THEN
        RAISE EXCEPTION 'ERR_SLUG_EXISTS: Slug already exists' USING ERRCODE = 'P0001';
    END IF;

    INSERT INTO posts
    (title,
     description,
     slug,
     content,
     author_name,
     tags,
     is_published,
     published_at)
    VALUES (p_title,
            p_description,
            p_slug,
            p_content,
            p_author_name,
            p_tags,
            p_is_published,
            CASE
                WHEN p_is_published = FALSE
                    THEN NULL
                ELSE NOW()
                END);
EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION '%: %', SQLSTATE, SQLERRM;
END
$$;

CREATE OR REPLACE FUNCTION posts_delete(
    p_post_id BIGINT
)
    RETURNS VOID
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF p_post_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM posts WHERE post_id = p_post_id) THEN
        RAISE EXCEPTION 'Post does not exist' USING ERRCODE = 'P0001';
    END IF;

    DELETE
    FROM posts p
    WHERE p.post_id = p_post_id;

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION '%: %', SQLSTATE, SQLERRM;
END
$$;

CREATE OR REPLACE FUNCTION posts_update(
    p_post_id BIGINT,
    p_title TEXT = NULL,
    p_description TEXT = NULL,
    p_slug TEXT = NULL,
    p_content TEXT = NULL,
    p_author_name TEXT = NULL,
    p_tags TEXT[] = NULL,
    p_is_published BOOLEAN = NULL
)
    RETURNS VOID
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF p_post_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM posts WHERE post_id = p_post_id) THEN
        RAISE EXCEPTION 'Post does not exist' USING ERRCODE = 'P0001';
    END IF;

    IF EXISTS (SELECT 1 FROM posts WHERE slug = p_slug) THEN
        RAISE EXCEPTION 'ERR_SLUG_EXISTS: Slug already exists' USING ERRCODE = 'P0002';
    END IF;

    UPDATE posts
    SET title        = COALESCE(NULLIF(p_title, ''), title),
        description  = COALESCE(NULLIF(p_description, ''), description),
        slug         = COALESCE(NULLIF(p_slug, ''), slug),
        content      = COALESCE(NULLIF(p_content, ''), content),
        author_name  = COALESCE(NULLIF(p_author_name, ''), author_name),
        tags         = COALESCE(p_tags, tags),
        is_published = COALESCE(p_is_published, is_published),
        published_at = CASE
                           WHEN COALESCE(p_is_published, is_published) = TRUE
                               THEN NOW()
            END,
        updated_at = NOW()
    WHERE post_id = p_post_id;


EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION '%: %', SQLSTATE, SQLERRM;
END
$$;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP FUNCTION IF EXISTS posts_update(
    BIGINT,
    TEXT,
    TEXT,
    TEXT,
    TEXT,
    TEXT[],
    BOOLEAN
);

DROP FUNCTION IF EXISTS posts_delete(BIGINT);

DROP FUNCTION IF EXISTS posts_insert(
    TEXT,
    TEXT,
    TEXT,
    TEXT,
    TEXT[],
    BOOLEAN
);

DROP FUNCTION IF EXISTS posts_get(BIGINT, TEXT);

DROP TABLE IF EXISTS posts;
-- +goose StatementEnd
