#Server Configuration
Server:
  address: "0.0.0.0:8000"

Logger:
  level: "info"
  is_development: true
  filepath: "./logs/logs_%Y%m%d%H%M.txt"

Auth:
  secret: "RWAjFqBWioBhkRvTDJDfuyJO7lONAET3onIz6wSWwaY="
  issuer: "Server"
  audience: "App"
  token_ttl: 15 #in minutes
  encryption_key: "dF9vL8eX2rN9qWmZT7Bv31kYXpA5csHd"
  valid_users:
    - devadiga.rohit

Database:
  host: dpg-d12jjls9c44c738cjmg0-a.virginia-postgres.render.com
  port: 5432
  user: amethyst
  password: Ov2Za80b9SN811wiGmuOR5m2oZYWoAkz
  database: blogs_z5le
  ssl_mode: require
  max_connection_idle_time: 30m
  max_connection_lifetime: 1h

Cache:
  host: localhost
  protocol: 3
  port: 6379
  user: rohbot
  password: admin
  db: 0
  max_retries: 3
  min_retry_backoff: 100ms
  max_retry_backoff: 1s
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_fifo: true
  pool_size: 50
  pool_timeout: 4s
  min_idle_conns: 10
  conn_max_idle_time: 30m
  conn_max_lifetime: 1h

